name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "d38a2a7e51e66c11e32778a92d85bca0", preview_id = "d38a2a7e51e66c11e32778a92d85bca0" }
]
