name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "f5ed02a98f8c47a6a5118e977ae31bba", preview_id = "f5ed02a98f8c47a6a5118e977ae31bba" }
]
